name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: WakaTime
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7649e3356f2b4e7b06d131f200548a61
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
